// import type { Metadata } from "next";
// import { Inter as FontSans } from "next/font/google";
// import "./globals.css";
// import { cn } from "@/lib/utils";
// import { ClerkProvider } from "@clerk/nextjs";

// const fontSans = FontSans({
//   subsets: ["latin"],
//   variable: "--font-sans",
// });

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <ClerkProvider>
//     <html lang="en">
//       <body className={fontSans.className}>{children}</body>
//     </html>
//     </ClerkProvider>
//   );
// }

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/Header";




const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
 
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode; 
}>) {
  return (
    
    <html lang="en">
      <body className={inter.className}>
      <ClerkProvider>
        
       <Header/>
        {children}
          
         {/* <Aboutpage/> */}
        
        </ClerkProvider>

        </body>
    </html>
  );
}
